name: Lint Terraform files

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
          terraform_version: ~1.3

      - name: Format check Terraform's files
        run: terraform fmt -check

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform's files
        run: terraform validate
