name: Test app

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: |
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install --no-cache-dir --upgrade -r requirements.txt

      - name: Test app
        run: |
          pytest
